/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pid.exercise.search;

/**
 * The purpose of this class is to provide static methods for searching integer arrays and does not need to be
 * instantiated.
 */
public class Search {

    public static int linearSearch(int[] array, int value) {
        for (int i = 0; i < array.length; i++) {
            if (array[i] == value)
                return i;
        }
        return -1;
    }

    public static int binarySearch(int[] array, int value) {
        int lowerIndex = 0;
        int higherIndex = array.length - 1;

        while (lowerIndex <= higherIndex) {

            int middleIndex = higherIndex / 2;

            if (array[middleIndex] < value) {
                for (lowerIndex = middleIndex + 1; lowerIndex <= higherIndex; lowerIndex++) {
                    if (array[lowerIndex] == value)
                        return lowerIndex;
                }

            } else if (array[middleIndex] > value) {
                for (higherIndex = middleIndex - 1; higherIndex >= lowerIndex; higherIndex--) {
                    if (array[higherIndex] == value)
                        return higherIndex;
                }

            } else
                return middleIndex;
        }
        return -1;
    }

    public static int binarySearchRecursive(int[] array, int value) {
        // TODO Implement recursive binary search
        return 0;
    }

}
